# Generated by Django 3.2.4 on 2021-07-29 03:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacoes', '0002_avaliacao_usuario'),
        ('comum', '0001_initial'),
        ('pontos', '0001_initial'),
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtracaoRestaurante',
            fields=[
                ('codigo', models.UUIDField(db_column='cd_atracao_restaurante', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('atracao', models.ForeignKey(db_column='cd_atracao', on_delete=django.db.models.deletion.DO_NOTHING, related_name='atracao', to='atracoes.atracao')),
            ],
            options={
                'db_table': 'tb_atracoes_restaurantes',
            },
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('codigo', models.UUIDField(db_column='cd_restaurante', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='restaurantes/media')),
                ('faixa_de_preco', models.PositiveIntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('atracao', models.ManyToManyField(db_column='cd_atracao_restaurante', related_name='atracao_restaurante', related_query_name='atracoes_restaurantes', through='restaurantes.AtracaoRestaurante', to='atracoes.Atracao')),
                ('avaliacao', models.ManyToManyField(db_column='cd_avaliacao_restaurante', related_name='avaliacao_restaurante', related_query_name='avaliacoes_restaurantes', to='avaliacoes.Avaliacao')),
                ('endereco', models.ForeignKey(db_column='cd_endereco', on_delete=django.db.models.deletion.DO_NOTHING, to='comum.endereco')),
                ('ponto_turistico', models.ForeignKey(db_column='cd_ponto_turistico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pontos.pontoturistico')),
            ],
            options={
                'db_table': 'tb_restaurantes',
            },
        ),
        migrations.AddField(
            model_name='atracaorestaurante',
            name='restaurante',
            field=models.ForeignKey(db_column='cd_restaurante', on_delete=django.db.models.deletion.DO_NOTHING, related_name='restaurante', to='restaurantes.restaurante'),
        ),
    ]
