# Generated by Django 3.2.4 on 2021-08-07 06:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioMotivo',
            fields=[
                ('codigo', models.UUIDField(db_column='cd_comentario-motivo', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='ds_motivo', max_length=250)),
            ],
            options={
                'db_table': 'tb_comentarios-motivos',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('codigo', models.UUIDField(db_column='cd_comentario', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('data', models.DateTimeField(auto_now=True, db_column='dt_data')),
                ('aprovado', models.BooleanField(default=False)),
                ('improprio', models.BooleanField(default=False)),
                ('motivo', models.ForeignKey(db_column='cd_comentariomotivo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='motivo_comentario', to='comentarios.comentariomotivo')),
            ],
            options={
                'db_table': 'tb_comentarios',
            },
        ),
    ]
