# Generated by Django 3.2.4 on 2021-06-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=20, null=True)),
                ('longitude', models.CharField(max_length=20, null=True)),
                ('descricao', models.TextField()),
                ('cep', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'tb_enderecos',
            },
        ),
    ]
