# Generated by Django 3.2.4 on 2021-08-07 06:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('comum', '0001_initial'),
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('codigo', models.UUIDField(db_column='cd_ponto_turistico', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nm_ponto_turistico', max_length=300)),
                ('descricao', models.TextField()),
                ('aprovado', models.BooleanField(db_column='fl_aprovado', default=False)),
                ('foto', models.ImageField(upload_to='media/pontos_turisticos')),
                ('atracoes', models.ManyToManyField(related_name='atracao_ponto_turistico', related_query_name='atracoes_pontos_turisticos', to='atracoes.Atracao')),
                ('avaliacoes', models.ManyToManyField(related_name='avaliacao_ponto_turistico', related_query_name='avaliacoes_pontos_turisticos', to='avaliacoes.Avaliacao')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco_ponto_turistico', related_query_name='enderecos_pontos_turisticos', to='comum.endereco')),
            ],
            options={
                'db_table': 'tb_pontos_turisticos',
            },
        ),
    ]
