# Generated by Django 3.2.4 on 2021-08-07 06:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('codigo', models.UUIDField(db_column='cd_avaliacao', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nota', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('comentario', models.ForeignKey(db_column='comentario_avaliacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comentario_avaliacao', to='comentarios.comentario')),
            ],
            options={
                'db_table': 'tb_avaliacoes',
            },
        ),
    ]
