# Generated by Django 3.2.4 on 2021-06-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_user_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='acesso',
            field=models.IntegerField(choices=[(1, 'COMUM'), (2, 'GUIA TURISTICO'), (3, 'DONO DE ATRACAO'), (4, 'HOSPEDAGEM'), (5, 'RESTAURANTES')], db_column='lv_acesso', default=1),
        ),
    ]
