# Generated by Django 3.2.3 on 2021-05-22 04:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atracoes',
            fields=[
                ('codigo', models.UUIDField(db_column='cd_atracao', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nm_atracao', max_length=250)),
                ('idade_minima', models.IntegerField()),
                ('descricao', models.TextField()),
                ('horario_abertura', models.DateTimeField()),
                ('horario_fechamento', models.DateTimeField()),
                ('ativo', models.BooleanField(db_column='fl_ativo', default=True)),
                ('funciona_feriados', models.BooleanField(db_column='fl_feriados')),
            ],
            options={
                'db_table': 'tb_atracoes',
            },
        ),
    ]
