# Generated by Django 3.2.4 on 2021-08-07 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comum', '0001_initial'),
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='endereco',
            field=models.ForeignKey(db_column='cd_endereco', on_delete=django.db.models.deletion.CASCADE, to='comum.endereco'),
        ),
    ]
