# Generated by Django 3.2.3 on 2021-05-30 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='endereco',
            field=models.ForeignKey(db_column='cd_endereco', default='', on_delete=django.db.models.deletion.CASCADE, to='comum.endereco'),
            preserve_default=False,
        ),
    ]
